### PR TITLE
Customizable logging configuration

### PR DESCRIPTION
**Pull request by bdamian**
Hi there!

I've added an option to customize logs produced by yacron. I've also wrote a note about it in README.

Motivation for the change was to find out when tasks has failed. I'm aware of the sentry integration though sometimes much simpler text file logs is enough.

### CODE REVIEW

**Comment by gjcarneiro** [comment]
To be honest, I would prefer to have this logging configuration as part of the main yacron config file.  Why split this into two config files?

**Comment by gjcarneiro** [comment]
Hi, I started work on #83 that will likely replace this PR.  But thanks for this work!  I used your idea and some of your code, but it has a different approach: I think it's a better user experience to have all configuration in a single place, instead of scattered.

**Comment by bdamian** [comment]
Thanks for your interest!
For me it's no difference where the extra config for logging would be. So I would follow PR #83

**Comment by gjcarneiro** [comment]
Closing in favour of #83.

**Comment by DheerajKhajuria** [comment]
Does it support logging to file using handler?

**Pull request closed without merging**
